### ISSUE TITLE
Lumen 5.5 Generation error 

### ISSUE THREAD

**Issue by tarekchida** [krlove/eloquent-model-generator#33]
Hi, 
I am using Lumen 5.5 and Php 7.1
I am trying to generate Model from my database but a got this error : 

```
  Type error: Argument 1 passed to Krlove\EloquentModelGenerator\Provider\GeneratorServiceProvider::Krlove\EloquentModelGenerator\Provider\{closure}() must be an instance of Krlove\EloquentModelGenerator\Provid  
  er\Krlove\EloquentModelGenerator\Provider\Illuminate\Foundation\Application, instance of Laravel\Lumen\Application given, called in  vendor/laravel/framework/src/Illuminate/Container/  
  Container.php on line 749    
```

Can you help please ?
Thank you

**Comment by Ryllaz** [comment]
I have the same error. Waiting for response

**Comment by alperenwayne** [comment]
Check the pull request.
https://github.com/krlove/eloquent-model-generator/pull/34

**Comment by tarekchida** [comment]
I move to Laravel to create my Models and then I used theme in Lumen

**Comment by mvik86** [comment]
As I checked, I found that artisan command is not working after installing krlove/eloquent-model-generator. I tried to execute "php artisan --version" and I got the same response.

earlier I used to use krlove/eloquent-model-generator but now I am searching for other solution because I am worried when we get any response. 

Also, install laravel to generate model I don't think a good solution but thanks for the reply it can be helpful for many other members.

Type error: Argument 1 passed to Krlove\EloquentModelGenerator\Provider\GeneratorServiceProvider::Krlove\EloquentModelGenerator\Provider\{closure}() must be an instance of Illuminate\Foundation\Application, instance of Laravel\Lumen
  \Application given, called in D:\xampp\htdocs\myproject\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 764

**Comment by MarkOdey** [comment]
Using lumen as well and I am getting this problem. 

 Uncaught ReflectionException: Class path.storage does not exist in /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Con  
  tainer.php:767                                                                                                                             
  Stack trace:                                                                                                                               
  #0 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('path.storage')     
  #1 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('path.sto  
  rage')                                                                                                                                     
  #2 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('path.s  
  torage', Array)                                                                                                                            
  #3 /var/app/current/vendor/laravel/lumen-framework/src/Application.php(221): Illuminate\Container\Container->make('path.storage', Array)   
  #4 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): Laravel\Lumen\Application->make('path.storage',   
  Array)                                                                                                                                     
  #5 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(865): app('path.storage')                               
  #6 /var/app/current/vendor/laravel/lu

**Comment by krlove** [comment]
Hi,
Lumen support added in version 1.3.0.
Sorry for so long delay.
