### ISSUE TITLE
models directive in laravel 8 

### ISSUE THREAD

**Issue by mikacode** [krlove/eloquent-model-generator#78]
noticed in laravel 8 
at the 'related'  parameter at relations it assume App/name_of_model
while laravel 8 changed the directive to App/Models/name_of_model

**Comment by krlove** [comment]
Thanks @mikacode , good point.
The best solution for this case would be to create a config as described here with following content:
```
return [
    'model_defaults' => [
        'output_path'     => 'Models',
    ],
];
```
Since the latest version of Eloquent Model Generator supports at the same time all Laravel versions starting from 5.0, it would be not convenient for me to determine the most sensible defaults for each version programmatically.
Anyway, I will take this case into account for future changes.

**Comment by xenogenesi** [comment]
Thanks for creating and sharing this tool, very useful.

With the config suggested the models are generated in the app/Models directory correctly, but with the wrong namespace, and the few relationship functions I've seen also had wrong namespace, took me a little while to understand why tinker wasn't working.
